export const MIGRATIONS_ESPERADAS = [
  '001_schema.sql',
  '002_policies.sql',
  '003_storage.sql',
  '004_ajustes.sql',
  '005_portal_paciente.sql',
  '006_saas_ia.sql',
  '007_bucket_publico.sql',
  '008_flexibilidade_dinamometria.sql',
  '009_bioimpedancia.sql',
  '010_sptech_dinamometria.sql',
  '011_ventilometria.sql',
  '012_cpf_paciente.sql',
  '013_pdf_config.sql',
  '014_portal_todos_modulos.sql',
  '015_biomecanica_anamnese_templates.sql',
  '016_rml_fixes.sql',
  '017_bucket_branding.sql',
  '018_anamnese_template_trigger.sql',
  '019_drop_bioimpedancia_impedancias.sql',
  '020_bucket_biomecanica.sql',
  '021_forca_dinamometria_tracao.sql',
  '022_forca_preensao_opcional_e_tipo.sql',
  '023_biomecanica_comentarios_graficos.sql',
  '024_schema_alignment_for_deploy.sql',
  '025_internal_access_and_evaluator_profile.sql',
  '026_paciente_tokens_clinica_policies.sql',
  '027_clinica_membership_rls_fix.sql',
  '028_clinica_instagram.sql',
  '029_biomecanica_video_posterior.sql',
  '030_patient_engagement_and_action_plan.sql',
  '031_consentimento_links.sql',
  '032_configuracoes_anamnese_termos_protocolos_fix.sql',
  '033_planos_acao_alimentar.sql',
  '034_ia_revisao_schema_alignment.sql',
  '035_fix_medfit_site_domain.sql',
  '036_pre_atendimento_tables_repair.sql',
  '037_consentimento_revogacao_e_anamnese_respostas.sql',
  '038_anamnese_historia_familiar_historico_medico.sql',
  '039_forca_contexto_esportivo_medeor.sql',
  '040_forca_tracao_whc06_metricas.sql',
  '041_paciente_dados_corporais_base.sql',
  '042_normalize_text_integrity.sql',
  '043_produtos_schema_alignment.sql',
  '044_produtos_catalogo_comercial.sql',
  '045_fonte_gordura_relatorio.sql',
  '046_catalogo_textos_clinica.sql',
  '047_central_evidencias_legais.sql',
  '048_produto_imagens_bucket_hardening.sql',
  '049_planos_alimentares_templates_padrao.sql',
  '050_prontuario_paciente.sql',
  '051_system_health_and_evidence_pdf.sql',
] as const;

export const ULTIMA_MIGRATION_ESPERADA =
  MIGRATIONS_ESPERADAS[MIGRATIONS_ESPERADAS.length - 1];
