import assert from 'node:assert/strict';
import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import { newJumpData, newJumpTrial, jumpSchema, jumpSummary, trialMetrics, trialWarnings, jumpComparable, jumpAnalysisUsable, jumpProtocolTechnique } from '../src/lib/jump-test';
import { jumpReportHtml, jumpEvolutionHtml } from '../src/lib/pdf/jump-test';
import { renderLaudoHTML } from '../src/lib/pdf/template';
import { promptJumpTest } from '../src/lib/ai/prompts';
import { jumpClinicalContext } from '../src/lib/jump-test';
import { formatCalendarDate } from '../src/lib/date';
import { validateEnteredJump } from '../src/lib/jump-test';

assert.equal(validateEnteredJump(newJumpTrial('sj', 'empty')).status, 'pendente');
assert.equal(validateEnteredJump({ ...newJumpTrial('sj', 'normal'), altura_cm: 30 }).status, 'valida');
assert.equal(validateEnteredJump({ ...newJumpTrial('cmj', 'flight'), voo_ms: 500 }).status, 'valida');
assert.equal(validateEnteredJump({ ...newJumpTrial('sj', 'high'), altura_cm: 300 }).status, 'pendente');
assert.equal(validateEnteredJump({ ...newJumpTrial('dj', 'contact'), altura_cm: 30 }).status, 'pendente');
assert.equal(validateEnteredJump({ ...newJumpTrial('dj', 'complete'), altura_cm: 30, contato_ms: 200 }).status, 'valida');
assert.equal(validateEnteredJump({ ...newJumpTrial('sj', 'excluded'), altura_cm: 30, status: 'excluida', justificativa: 'Tecnica inadequada' }).status, 'excluida');
assert.equal(validateEnteredJump({ ...newJumpTrial('sj', 'inconsistent'), altura_cm: 30, voo_ms: 100 }).status, 'pendente');
assert.equal(newJumpTrial('vj', 'vj-technique').tecnica_bracos, 'cintura');
assert.equal(newJumpTrial('cmj', 'cmj-technique').tecnica_bracos, 'livres');

const d = newJumpData();
d.apto = d.familiarizacao = true; d.peso_kg = 75;
d.protocolos = ['sj', 'vj', 'cmj', 'dj', 'unilateral_d', 'unilateral_e', 'repetidos'];
d.repetidos_serie_completa = true;
for (const p of d.protocolos) for (let i = 0; i < (p === 'repetidos' ? 12 : 3); i++) {
  const h = p === 'sj' ? 25 : p === 'cmj' ? 35 : p === 'unilateral_d' ? 20 : p === 'unilateral_e' ? 18 : 30;
  d.tentativas.push({ ...newJumpTrial(p, `${p}-${i}`), altura_cm: h, contato_ms: p === 'dj' || p === 'repetidos' ? 200 : null, potencia_w: 3000, status: 'valida' });
}
assert.equal(jumpSchema.safeParse(d).success, true);
const summary = jumpSummary(d);
assert.equal(formatCalendarDate('2026-06-15'), '15/06/2026');
assert.equal(formatCalendarDate('invalid'), 'invalid');
const simulatedContext = jumpClinicalContext({ ...d, observacoes: 'DADOS SIMULADOS para teste de software' });
assert.equal('resultados' in simulatedContext, false);
assert.equal('simulado' in simulatedContext && simulatedContext.simulado, true);
assert.equal('resultados' in jumpClinicalContext(d), true);
assert.equal(summary.pronto, true);
assert.equal(summary.eur_altura, 1.2);
assert.equal(summary.eur_protocolo, 'vj');
const legacy = { ...d, protocolos: d.protocolos.filter(p => p !== 'vj'), tentativas: d.tentativas.filter(t => t.protocolo !== 'vj').map(({ tecnica_bracos: _, ...t }) => t) };
assert.equal(jumpSchema.safeParse(legacy).success, true, 'Coleta anterior sem VJ nem tecnica por tentativa deve continuar valida');
assert.equal(jumpSummary(legacy).eur_protocolo, 'cmj');
assert.equal(jumpSummary(legacy).eur_altura, 1.4);
assert.equal(summary.assimetria_altura_percent, 10);
assert.equal(summary.grupos.find(x => x.protocolo === 'dj')?.rsi_medio, 1.4999999999999998);
assert.equal(trialMetrics(d.tentativas[0], 75).potencia_w_kg, 40);
assert.equal(trialMetrics(d.tentativas[0], null).potencia_w_kg, null);
assert.equal(trialMetrics(d.tentativas[0], 75).altura_mm, 250);
const fromFlight = { ...newJumpTrial('cmj', 'f'), voo_ms: 500 };
assert.ok(Math.abs(trialMetrics(fromFlight, null).altura_cm! - 30.64578125) < 0.00001);
assert.equal(trialMetrics(newJumpTrial('cmj', 'empty'), null).altura_cm, null);
assert.equal(trialMetrics({ ...d.tentativas[0], contato_ms: 200 }, 75).rsi, null, 'SJ must not receive DJ RSI');
const suspicious = { ...newJumpTrial('cmj', 'suspect'), altura_cm: 242, voo_ms: 1405, status: 'valida' as const };
assert.ok(trialWarnings(suspicious).length);
const bad = { ...d, tentativas: d.tentativas.map(t => t.id === 'cmj-0' ? suspicious : t) };
assert.equal(jumpSummary(bad).pronto, false);
assert.equal(jumpSummary(bad).grupos.find(g => g.protocolo === 'cmj')?.n, 2);
assert.equal(jumpSchema.safeParse({ ...d, tentativas: [{ ...suspicious, status: 'excluida' }] }).success, false);
assert.equal(jumpSchema.safeParse({ ...d, peso_kg: -1 }).success, false);
assert.equal(jumpSchema.safeParse({ ...d, duracao_s: 30 }).success, false);
assert.equal(jumpSchema.safeParse({ ...d, tentativas: [...d.tentativas, d.tentativas[0]] }).success, false);
assert.equal(jumpSummary({ ...d, repetidos_serie_completa: false }).pronto, false);
assert.equal(jumpSummary({ ...d, familiarizacao: false }).pronto, false);
assert.equal(jumpSummary({ ...d, tentativas: [...d.tentativas, { ...d.tentativas[0], id: 'fourth' }] }).pronto, false);
assert.equal(jumpSummary({ ...d, tentativas: d.tentativas.map(t => t.protocolo === 'dj' ? { ...t, contato_ms: null, justificativa: 'reviewed' } : t) }).pronto, false);
assert.equal(jumpComparable(d, { ...d, altura_queda_cm: 20 }, 'dj'), false);
assert.equal(jumpComparable(d, { ...d, altura_queda_cm: 20 }, 'cmj'), true);
assert.equal(jumpComparable(d, { ...d, bracos: 'livres' }, 'cmj'), true, 'Tecnica explicita do CMJ nao depende do campo legado global');
assert.equal(jumpComparable(d, { ...d, tentativas: d.tentativas.map(t => t.protocolo === 'cmj' ? { ...t, tecnica_bracos: 'cintura' as const } : t) }, 'cmj'), false);
assert.match(jumpProtocolTechnique(d, 'vj'), /maos na cintura/);
assert.match(jumpProtocolTechnique(d, 'cmj'), /bracos livres/);
assert.equal(jumpAnalysisUsable({ tipo: 'jump_test', conteudo: { _jump_updated_at: 'old' } }, { updated_at: 'new' }), false);
assert.equal(jumpAnalysisUsable({ tipo: 'jump_test', conteudo: { _jump_updated_at: 'same' } }, { updated_at: 'same' }), true);
assert.equal(jumpAnalysisUsable({ tipo: 'anamnese' }, { updated_at: 'new' }), true);
const prompt = promptJumpTest({ nome: 'Pessoa ficticia', sexo: 'F', idade: 35 }, { ...d, contexto_integrado: { data_atual: '2026-09-23', historico: [] } });
assert.match(prompt.system, /medicamentos passados nao sao uso atual/);
assert.match(prompt.system, /simulados, ficticios ou de teste/);
assert.match(prompt.user, /contextual/);
assert.match(prompt.user, /2026-09-23/);
assert.match(jumpEvolutionHtml(d, { ...d, tentativas: d.tentativas.map(t => t.protocolo === 'cmj' ? { ...t, tecnica_bracos: 'cintura' as const } : t) }), /Nao comparavel/);
assert.doesNotMatch(jumpReportHtml({ ...d, observacoes: '<script>alert(1)</script>' }), /<script>alert/);
assert.doesNotMatch(jumpReportHtml(bad, 'SHOULD_NOT_SHOW'), /SHOULD_NOT_SHOW/);

const html = renderLaudoHTML({ paciente: { nome: 'Pessoa ficticia - teste', sexo: 'M', idade: 30, data_nascimento: '1996-01-01' }, avaliador: { nome: 'Avaliador teste' }, avaliacao: { data: '2026-09-23', tipo: 'personalizado' }, modulos: { jump_test: true }, dados: { jump_test: d }, scores: { global: null, postura: null, composicao_corporal: null, forca: null, cardiorrespiratorio: null } });
assert.match(html, /Jump Test/);
assert.match(html, /RSI m\/s/);
assert.match(html, /Vertical Jump \(VJ\)/);
assert.match(html, /CMJ unilateral direito/);
const migration = readFileSync('supabase/migrations/20260924024216_jump_test.sql', 'utf8');
assert.match(migration, /enable row level security/);
assert.match(migration, /with check \(public.user_owns_avaliacao\(avaliacao_id\)\)/);
assert.match(migration, /revoke all on public.jump_test from anon/);
assert.doesNotMatch(migration, /security definer/i);
mkdirSync('tmp/jump-test', { recursive: true });
writeFileSync('tmp/jump-test/fixture.json', JSON.stringify(d));
writeFileSync('tmp/jump-test/laudo.html', html);
const compact = { ...d, protocolos: d.protocolos.filter(p => ['sj', 'vj', 'cmj', 'dj'].includes(p)), tentativas: d.tentativas.filter(t => ['sj', 'vj', 'cmj', 'dj'].includes(t.protocolo)) };
writeFileSync('tmp/jump-test/compact.html', renderLaudoHTML({ paciente: { nome: 'Teste compacto', sexo: 'M', idade: 30, data_nascimento: '1996-01-01' }, avaliador: { nome: 'Teste' }, avaliacao: { data: '2026-09-25', tipo: 'personalizado' }, modulos: { jump_test: true }, dados: { jump_test: compact }, scores: {} as any }));
assert.match(html, /<li>Jump Test —/);
console.log('Jump Test: calculo, VJ/CMJ, revisao, seguranca, contexto e relatorio aprovados.');
